SELECT * FROM TP_MUSTEAT;

SELECT * FROM TP_LIST;

SELECT * FROM TP_MEMBER

SELECT * FROM MEMBER;

SELECT * FROM BBS;


DROP TABLE TP_MUSTEAT
CASCADE CONSTRAINTS;



DROP TABLE BBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BBS;

CREATE TABLE BBS(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,		-- 글의 작성자
	
	REF NUMBER(8) NOT NULL,			-- 답변을 설정
	STEP NUMBER(8) NOT NULL,
	DEPTH NUMBER(8) NOT NULL,
	
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WDATE DATE NOT NULL,
	
	DEL NUMBER(1) NOT NULL,			-- 삭제 판단
	READCOUNT NUMBER(8) NOT NULL	-- 조회수
);
SELECT * FROM BBS;

CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;

ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_ID FOREIGN KEY(ID)  
REFERENCES MEMBER(ID);


