SELECT * FROM TP_MEMBER;

 SELECT TP_ME_SEQ, 
 TP_ME_PLACE, 
 TP_ME_ID, 
 TP_ME_NAME, 
  TP_ME_TITLE,
 TP_ME_CONTENT, 
 TP_ME_FILENAME, 
 TP_ME_NEWFILENAME,
 TP_ME_READCOUNT, 
 TP_ME_DOWNCOUNT, 
 TP_ME_REGDATE
 FROM TP_MUSTEAT
 ORDER BY TP_ME_SEQ DESC;
 
 SELECT TP_ME_SEQ, TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE,
 TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, 
 TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE 
 FROM TP_MUSTEAT 
 WHERE TP_ME_CONTENT 
 LIKE '%순댓국%'  
 ORDER BY TP_ME_SEQ DESC; 
 
SELECT TP_ME_SEQ, TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME,
TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE
FROM TP_MUSTEAT
WHERE TP_ME_SEQ=1;


DROP TABLE TP_MUSTEAT
CASCADE CONSTRAINTS;

DROP SEQUENCE TP_ME_SEQ_MUSTEAT;


CREATE TABLE TP_MUSTEAT(

	TP_ME_SEQ NUMBER(8) PRIMARY KEY,
	TP_ME_PLACE VARCHAR2(50) NOT NULL,
	TP_ME_ID VARCHAR2(50) NOT NULL, 
	TP_ME_NAME VARCHAR2(50) NOT NULL,
	
	TP_ME_TITLE VARCHAR2(200) NOT NULL,
	TP_ME_CONTENT VARCHAR2(4000) NOT NULL,
	
	TP_ME_FILENAME VARCHAR2(50) NOT NULL,
	TP_ME_NEWFILENAME VARCHAR2(50) NOT NULL,
	TP_ME_READCOUNT NUMBER(8) NOT NULL,
	TP_ME_DOWNCOUNT NUMBER(8) NOT NULL,
	TP_ME_REGDATE DATE NOT NULL,
	TP_ME_LIKE NUMBER(8) NULL
	
);




CREATE SEQUENCE TP_ME_SEQ_MUSTEAT
START WITH 1
INCREMENT BY 1;
-------------매칭 테이블
CREATE TABLE TP_MATCH(

	TP_MA_SEQ NUMBER(8) PRIMARY KEY,
	TP_MA_PLACE VARCHAR2(50) NOT NULL,
	TP_MA_ID VARCHAR2(50) NOT NULL, 
	TP_MA_NAME VARCHAR2(50) NOT NULL,
	
	TP_MA_TITLE VARCHAR2(200) NOT NULL,
	TP_MA_CONTENT VARCHAR2(4000) NOT NULL,
	
	TP_MA_FILENAME VARCHAR2(50) NOT NULL,
	TP_MA_NEWFILENAME VARCHAR2(50) NOT NULL,
	TP_MA_READCOUNT NUMBER(8) NOT NULL,
	TP_MA_DOWNCOUNT NUMBER(8) NOT NULL,
	TP_MA_FIRDATE DATE NOT NULL,
	TP_MA_LASDATE DATE NOT NULL
	
	
);




CREATE SEQUENCE TP_MA_SEQ_MATCH
START WITH 1
INCREMENT BY 1;

SELECT * FROM TP_MUSTEAT;

SELECT * FROM TP_LIST

CREATE TABLE TP_MUSTEAT(

	TP_ME_SEQ NUMBER(8) PRIMARY KEY,
	TP_ME_PLACE VARCHAR2(50) NOT NULL,
	TP_ME_ID VARCHAR2(50) NOT NULL, 
	TP_ME_NAME VARCHAR2(50) NOT NULL,
	
	TP_ME_TITLE VARCHAR2(200) NOT NULL,
	TP_ME_CONTENT VARCHAR2(4000) NOT NULL,
	
	TP_ME_FILENAME VARCHAR2(50) NOT NULL,
	TP_ME_NEWFILENAME VARCHAR2(50) NOT NULL,
	TP_ME_READCOUNT NUMBER(8) NOT NULL,
	TP_ME_DOWNCOUNT NUMBER(8) NOT NULL,
	TP_ME_REGDATE DATE NOT NULL
);

----- 조회수별로 리스트
SELECT TP_ME_SEQ, TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT
 , TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE
FROM TP_MUSTEAT
WHERE ROWNUM <=3
ORDER BY TP_ME_READCOUNT desc;
	


SELECT RNUM, TP_ME_SEQ, TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT
 , TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE, TP_ME_LIKE
FROM (SELECT ROW_NUMBER()OVER(ORDER BY TP_ME_READCOUNT DESC)AS RNUM, TP_ME_SEQ, TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT
 , TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE, TP_ME_LIKE
 FROM TP_MUSTEAT)
 WHERE RNUM <=3
	
----- 좋아요 추가
ALTER TABLE 



-----

DROP TABLE TP_COMMENT
CASCADE CONSTRAINTS;

DROP SEQUENCE TP_COMMENT_SEQ;

SELECT * FROM TP_COMMENT

CREATE TABLE TP_COMMENT(

	COMMENT_SEQ NUMBER(8) PRIMARY KEY,
	COMMENT_LIST_SEQ NUMBER(8) NOT NULL,
	COMMENT_ID VARCHAR2(50) NOT NULL, 
	COMMENT_DATE DATE NOT NULL,
	COMMENT_CONTENT VARCHAR2(4000) NOT NULL,
	CONSTRAINT FK_SEQ FOREIGN KEY(COMMENT_LIST_SEQ)
	REFERENCES TP_MUSTEAT(TP_ME_SEQ)


);

CREATE SEQUENCE TP_COMMENT_SEQ
START WITH 1
INCREMENT BY 1

SELECT*FROM TP_MEMBER




ALTER TABLE TP_MUSTEAT
ADD CONSTRAINT FK_ID_0 FOREIGN KEY(TP_ME_SEQ)
REFERENCES TP_MEMBER(TP_ME_SEQ);

-------------------- TP_COMMENT
SELECT * FROM TP_COMMENT;
CREATE TABLE TP_COMMENT
(
    COMMENT_SEQ         NUMBER            NOT NULL, 
    COMMENT_ME_SEQ      NUMBER             NULL, 
    COMMENT_TP_SEQ      NUMBER             NULL, 
    COMMENT_MA_SEQ      NUMBER             NULL, 
    COMMENT_ID          VARCHAR2(50)      NOT NULL, 
    COMMENT_DATE        DATE              NOT NULL, 
    COMMENT_CONTENT     VARCHAR2(4000)    NOT NULL, 
    CONSTRAINT TP_COMMENT_PK PRIMARY KEY (COMMENT_SEQ)
)
/
---------------------------------

INSERT INTO TP_MEMBER(TP_M_SEQ, TP_M_ID, TP_M_PWD, TP_M_EMAIL, TP_M_DEL, TP_M_AUTH, TP_M_JOINDATE, TP_M_LASTLOGIN)
VALUES(TP_ME_SEQ_MUSTEAT.NEXTVAL)



SELECT * FROM TP_MUSTEAT
WHERE TP_ME_SEQ=33 ;

DELETE FROM TP_MUSTEAT 
WHERE TP_ME_SEQ=33;

DELETE FROM TP_COMMENT a, TP_MUSTEAT b
WHERE a.COMMENT_ME_SEQ = b.TP_ME_SEQ 

SELECT * FROM TP_COMMENT

DELETE FROM 
(SELECT a.COMMENT_ME_SEQ, b.TP_ME_SEQ
FROM TP_COMMENT a, TP_MUSTEAT b
WHERE a.COMMENT_ME_SEQ = TP_ME_SEQ) c
WHERE c.TP_ME_SEQ=33;
-- 삭제할때 자식테이블을 먼저지우고 부모테이블을 지운다



------------------------
ALTER TABLE TP_COMMENT
ADD CONSTRAINT FK_ID_ME FOREIGN KEY(COMMENT_ME_SEQ)
REFERENCES TP_MUSTEAT(TP_ME_SEQ);

ALTER TABLE TP_COMMENT
ADD CONSTRAINT FK_ID_TP FOREIGN KEY(COMMENT_TP_SEQ )
REFERENCES TP_LIST(TP_L_SEQ);

ALTER TABLE TP_COMMENT
ADD CONSTRAINT FK_ID_MA FOREIGN KEY(COMMENT_MA_SEQ )
REFERENCES TP_MATCH(TP_MA_SEQ)


CREATE SEQUENCE TP_COMMENT_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TP_COMMENT_AI_TRG
BEFORE INSERT ON TP_COMMENT 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TP_COMMENT_SEQ.NEXTVAL
    INTO :NEW.COMMENT_SEQ
    FROM DUAL;
END;
/

--DROP TRIGGER TP_COMMENT_AI_TRG;
/

--DROP SEQUENCE TP_COMMENT_SEQ;
/

COMMENT ON TABLE TP_COMMENT IS '댓글기능테이블'
/

COMMENT ON COLUMN TP_COMMENT.COMMENT_SEQ IS '댓글고유번호'
/

COMMENT ON COLUMN TP_COMMENT.COMMENT_ME_SEQ IS '받아온맛집부모글번호'
/

COMMENT ON COLUMN TP_COMMENT.COMMENT_B_SEQ IS '받아온자유부모글번호'
/

COMMENT ON COLUMN TP_COMMENT.COMMENT_LIST_SEQ IS '받아온게시글부모글번호'
/

COMMENT ON COLUMN TP_COMMENT.COMMENT_ID IS '작성자아이디'
/

COMMENT ON COLUMN TP_COMMENT.COMMENT_DATE IS '댓글작성일'
/

COMMENT ON COLUMN TP_COMMENT.COMMENT_CONTENT IS '댓글내용'
/



INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 001', 'TP_ME_ID 001', 'TP_ME_NAME 001', 'TP_ME_TITLE 001', 'TP_ME_CONTENT 001', 'TP_ME_FILENAME 001', 'TP_ME_NEWFILENAME001', 001, 001, sysdate)
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 002', 'TP_ME_ID 002', 'TP_ME_NAME 002', 'TP_ME_TITLE 002', 'TP_ME_CONTENT 002', 'TP_ME_FILENAME 002', 'TP_ME_NEWFILENAME002', 002, 002, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 003', 'TP_ME_ID 003', 'TP_ME_NAME 003', 'TP_ME_TITLE 003', 'TP_ME_CONTENT 003', 'TP_ME_FILENAME 003', 'TP_ME_NEWFILENAME003', 003, 003, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 004', 'TP_ME_ID 004', 'TP_ME_NAME 004', 'TP_ME_TITLE 004', 'TP_ME_CONTENT 004', 'TP_ME_FILENAME 004', 'TP_ME_NEWFILENAME004', 004, 004, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 005', 'TP_ME_ID 005', 'TP_ME_NAME 005', 'TP_ME_TITLE 005', 'TP_ME_CONTENT 005', 'TP_ME_FILENAME 005', 'TP_ME_NEWFILENAME005', 005, 005, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 006', 'TP_ME_ID 006', 'TP_ME_NAME 006', 'TP_ME_TITLE 006', 'TP_ME_CONTENT 006', 'TP_ME_FILENAME 006', 'TP_ME_NEWFILENAME006', 006, 006, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 007', 'TP_ME_ID 007', 'TP_ME_NAME 007', 'TP_ME_TITLE 007', 'TP_ME_CONTENT 007', 'TP_ME_FILENAME 007', 'TP_ME_NEWFILENAME007', 007, 007, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 008', 'TP_ME_ID 008', 'TP_ME_NAME 008', 'TP_ME_TITLE 008', 'TP_ME_CONTENT 008', 'TP_ME_FILENAME 008', 'TP_ME_NEWFILENAME008', 008, 008, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 009', 'TP_ME_ID 009', 'TP_ME_NAME 009', 'TP_ME_TITLE 009', 'TP_ME_CONTENT 009', 'TP_ME_FILENAME 009', 'TP_ME_NEWFILENAME009', 009, 009, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 010', 'TP_ME_ID 010', 'TP_ME_NAME 010', 'TP_ME_TITLE 010', 'TP_ME_CONTENT 010', 'TP_ME_FILENAME 010', 'TP_ME_NEWFILENAME010', 010, 010, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 011', 'TP_ME_ID 011', 'TP_ME_NAME 011', 'TP_ME_TITLE 011', 'TP_ME_CONTENT 011', 'TP_ME_FILENAME 011', 'TP_ME_NEWFILENAME011', 011, 011, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 012', 'TP_ME_ID 012', 'TP_ME_NAME 012', 'TP_ME_TITLE 012', 'TP_ME_CONTENT 012', 'TP_ME_FILENAME 012', 'TP_ME_NEWFILENAME012', 012, 012, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 013', 'TP_ME_ID 013', 'TP_ME_NAME 013', 'TP_ME_TITLE 013', 'TP_ME_CONTENT 013', 'TP_ME_FILENAME 013', 'TP_ME_NEWFILENAME013', 013, 013, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 014', 'TP_ME_ID 014', 'TP_ME_NAME 014', 'TP_ME_TITLE 014', 'TP_ME_CONTENT 014', 'TP_ME_FILENAME 014', 'TP_ME_NEWFILENAME014', 014, 014, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 015', 'TP_ME_ID 015', 'TP_ME_NAME 015', 'TP_ME_TITLE 015', 'TP_ME_CONTENT 015', 'TP_ME_FILENAME 015', 'TP_ME_NEWFILENAME015', 015, 015, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 016', 'TP_ME_ID 016', 'TP_ME_NAME 016', 'TP_ME_TITLE 016', 'TP_ME_CONTENT 016', 'TP_ME_FILENAME 016', 'TP_ME_NEWFILENAME016', 016, 016, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 017', 'TP_ME_ID 017', 'TP_ME_NAME 017', 'TP_ME_TITLE 017', 'TP_ME_CONTENT 017', 'TP_ME_FILENAME 017', 'TP_ME_NEWFILENAME017', 017, 017, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 018', 'TP_ME_ID 018', 'TP_ME_NAME 018', 'TP_ME_TITLE 018', 'TP_ME_CONTENT 018', 'TP_ME_FILENAME 018', 'TP_ME_NEWFILENAME018', 018, 018, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 019', 'TP_ME_ID 019', 'TP_ME_NAME 019', 'TP_ME_TITLE 019', 'TP_ME_CONTENT 019', 'TP_ME_FILENAME 019', 'TP_ME_NEWFILENAME019', 019, 019, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 020', 'TP_ME_ID 020', 'TP_ME_NAME 020', 'TP_ME_TITLE 020', 'TP_ME_CONTENT 020', 'TP_ME_FILENAME 020', 'TP_ME_NEWFILENAME020', 020, 020, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 021', 'TP_ME_ID 021', 'TP_ME_NAME 021', 'TP_ME_TITLE 021', 'TP_ME_CONTENT 021', 'TP_ME_FILENAME 021', 'TP_ME_NEWFILENAME021', 021, 021, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 022', 'TP_ME_ID 022', 'TP_ME_NAME 022', 'TP_ME_TITLE 022', 'TP_ME_CONTENT 022', 'TP_ME_FILENAME 022', 'TP_ME_NEWFILENAME022', 022, 022, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 023', 'TP_ME_ID 023', 'TP_ME_NAME 023', 'TP_ME_TITLE 023', 'TP_ME_CONTENT 023', 'TP_ME_FILENAME 023', 'TP_ME_NEWFILENAME023', 023, 023, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 024', 'TP_ME_ID 024', 'TP_ME_NAME 024', 'TP_ME_TITLE 024', 'TP_ME_CONTENT 024', 'TP_ME_FILENAME 024', 'TP_ME_NEWFILENAME024', 024, 024, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 025', 'TP_ME_ID 025', 'TP_ME_NAME 025', 'TP_ME_TITLE 025', 'TP_ME_CONTENT 025', 'TP_ME_FILENAME 025', 'TP_ME_NEWFILENAME025', 025, 025, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 026', 'TP_ME_ID 026', 'TP_ME_NAME 026', 'TP_ME_TITLE 026', 'TP_ME_CONTENT 026', 'TP_ME_FILENAME 026', 'TP_ME_NEWFILENAME026', 026, 026, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 027', 'TP_ME_ID 027', 'TP_ME_NAME 027', 'TP_ME_TITLE 027', 'TP_ME_CONTENT 027', 'TP_ME_FILENAME 027', 'TP_ME_NEWFILENAME027', 027, 027, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 028', 'TP_ME_ID 028', 'TP_ME_NAME 028', 'TP_ME_TITLE 028', 'TP_ME_CONTENT 028', 'TP_ME_FILENAME 028', 'TP_ME_NEWFILENAME028', 028, 028, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 029', 'TP_ME_ID 029', 'TP_ME_NAME 029', 'TP_ME_TITLE 029', 'TP_ME_CONTENT 029', 'TP_ME_FILENAME 029', 'TP_ME_NEWFILENAME029', 029, 029, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 030', 'TP_ME_ID 030', 'TP_ME_NAME 030', 'TP_ME_TITLE 030', 'TP_ME_CONTENT 030', 'TP_ME_FILENAME 030', 'TP_ME_NEWFILENAME030', 030, 030, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 031', 'TP_ME_ID 031', 'TP_ME_NAME 031', 'TP_ME_TITLE 031', 'TP_ME_CONTENT 031', 'TP_ME_FILENAME 031', 'TP_ME_NEWFILENAME031', 031, 031, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 032', 'TP_ME_ID 032', 'TP_ME_NAME 032', 'TP_ME_TITLE 032', 'TP_ME_CONTENT 032', 'TP_ME_FILENAME 032', 'TP_ME_NEWFILENAME032', 032, 032, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 033', 'TP_ME_ID 033', 'TP_ME_NAME 033', 'TP_ME_TITLE 033', 'TP_ME_CONTENT 033', 'TP_ME_FILENAME 033', 'TP_ME_NEWFILENAME033', 033, 033, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 034', 'TP_ME_ID 034', 'TP_ME_NAME 034', 'TP_ME_TITLE 034', 'TP_ME_CONTENT 034', 'TP_ME_FILENAME 034', 'TP_ME_NEWFILENAME034', 034, 034, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 035', 'TP_ME_ID 035', 'TP_ME_NAME 035', 'TP_ME_TITLE 035', 'TP_ME_CONTENT 035', 'TP_ME_FILENAME 035', 'TP_ME_NEWFILENAME035', 035, 035, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 036', 'TP_ME_ID 036', 'TP_ME_NAME 036', 'TP_ME_TITLE 036', 'TP_ME_CONTENT 036', 'TP_ME_FILENAME 036', 'TP_ME_NEWFILENAME036', 036, 036, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 037', 'TP_ME_ID 037', 'TP_ME_NAME 037', 'TP_ME_TITLE 037', 'TP_ME_CONTENT 037', 'TP_ME_FILENAME 037', 'TP_ME_NEWFILENAME037', 037, 037, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 038', 'TP_ME_ID 038', 'TP_ME_NAME 038', 'TP_ME_TITLE 038', 'TP_ME_CONTENT 038', 'TP_ME_FILENAME 038', 'TP_ME_NEWFILENAME038', 038, 038, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 039', 'TP_ME_ID 039', 'TP_ME_NAME 039', 'TP_ME_TITLE 039', 'TP_ME_CONTENT 039', 'TP_ME_FILENAME 039', 'TP_ME_NEWFILENAME039', 039, 039, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 040', 'TP_ME_ID 040', 'TP_ME_NAME 040', 'TP_ME_TITLE 040', 'TP_ME_CONTENT 040', 'TP_ME_FILENAME 040', 'TP_ME_NEWFILENAME040', 040, 040, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 041', 'TP_ME_ID 041', 'TP_ME_NAME 041', 'TP_ME_TITLE 041', 'TP_ME_CONTENT 041', 'TP_ME_FILENAME 041', 'TP_ME_NEWFILENAME041', 041, 041, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 042', 'TP_ME_ID 042', 'TP_ME_NAME 042', 'TP_ME_TITLE 042', 'TP_ME_CONTENT 042', 'TP_ME_FILENAME 042', 'TP_ME_NEWFILENAME042', 042, 042, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 043', 'TP_ME_ID 043', 'TP_ME_NAME 043', 'TP_ME_TITLE 043', 'TP_ME_CONTENT 043', 'TP_ME_FILENAME 043', 'TP_ME_NEWFILENAME043', 043, 043, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 044', 'TP_ME_ID 044', 'TP_ME_NAME 044', 'TP_ME_TITLE 044', 'TP_ME_CONTENT 044', 'TP_ME_FILENAME 044', 'TP_ME_NEWFILENAME044', 044, 044, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 045', 'TP_ME_ID 045', 'TP_ME_NAME 045', 'TP_ME_TITLE 045', 'TP_ME_CONTENT 045', 'TP_ME_FILENAME 045', 'TP_ME_NEWFILENAME045', 045, 045, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 046', 'TP_ME_ID 046', 'TP_ME_NAME 046', 'TP_ME_TITLE 046', 'TP_ME_CONTENT 046', 'TP_ME_FILENAME 046', 'TP_ME_NEWFILENAME046', 046, 046, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 047', 'TP_ME_ID 047', 'TP_ME_NAME 047', 'TP_ME_TITLE 047', 'TP_ME_CONTENT 047', 'TP_ME_FILENAME 047', 'TP_ME_NEWFILENAME047', 047, 047, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 048', 'TP_ME_ID 048', 'TP_ME_NAME 048', 'TP_ME_TITLE 048', 'TP_ME_CONTENT 048', 'TP_ME_FILENAME 048', 'TP_ME_NEWFILENAME048', 048, 048, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 049', 'TP_ME_ID 049', 'TP_ME_NAME 049', 'TP_ME_TITLE 049', 'TP_ME_CONTENT 049', 'TP_ME_FILENAME 049', 'TP_ME_NEWFILENAME049', 049, 049, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 050', 'TP_ME_ID 050', 'TP_ME_NAME 050', 'TP_ME_TITLE 050', 'TP_ME_CONTENT 050', 'TP_ME_FILENAME 050', 'TP_ME_NEWFILENAME050', 050, 050, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 051', 'TP_ME_ID 051', 'TP_ME_NAME 051', 'TP_ME_TITLE 051', 'TP_ME_CONTENT 051', 'TP_ME_FILENAME 051', 'TP_ME_NEWFILENAME051', 051, 051, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 052', 'TP_ME_ID 052', 'TP_ME_NAME 052', 'TP_ME_TITLE 052', 'TP_ME_CONTENT 052', 'TP_ME_FILENAME 052', 'TP_ME_NEWFILENAME052', 052, 052, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 053', 'TP_ME_ID 053', 'TP_ME_NAME 053', 'TP_ME_TITLE 053', 'TP_ME_CONTENT 053', 'TP_ME_FILENAME 053', 'TP_ME_NEWFILENAME053', 053, 053, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 054', 'TP_ME_ID 054', 'TP_ME_NAME 054', 'TP_ME_TITLE 054', 'TP_ME_CONTENT 054', 'TP_ME_FILENAME 054', 'TP_ME_NEWFILENAME054', 054, 054, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 055', 'TP_ME_ID 055', 'TP_ME_NAME 055', 'TP_ME_TITLE 055', 'TP_ME_CONTENT 055', 'TP_ME_FILENAME 055', 'TP_ME_NEWFILENAME055', 055, 055, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 056', 'TP_ME_ID 056', 'TP_ME_NAME 056', 'TP_ME_TITLE 056', 'TP_ME_CONTENT 056', 'TP_ME_FILENAME 056', 'TP_ME_NEWFILENAME056', 056, 056, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 057', 'TP_ME_ID 057', 'TP_ME_NAME 057', 'TP_ME_TITLE 057', 'TP_ME_CONTENT 057', 'TP_ME_FILENAME 057', 'TP_ME_NEWFILENAME057', 057, 057, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 058', 'TP_ME_ID 058', 'TP_ME_NAME 058', 'TP_ME_TITLE 058', 'TP_ME_CONTENT 058', 'TP_ME_FILENAME 058', 'TP_ME_NEWFILENAME058', 058, 058, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 059', 'TP_ME_ID 059', 'TP_ME_NAME 059', 'TP_ME_TITLE 059', 'TP_ME_CONTENT 059', 'TP_ME_FILENAME 059', 'TP_ME_NEWFILENAME059', 059, 059, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 060', 'TP_ME_ID 060', 'TP_ME_NAME 060', 'TP_ME_TITLE 060', 'TP_ME_CONTENT 060', 'TP_ME_FILENAME 060', 'TP_ME_NEWFILENAME060', 060, 060, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 061', 'TP_ME_ID 061', 'TP_ME_NAME 061', 'TP_ME_TITLE 061', 'TP_ME_CONTENT 061', 'TP_ME_FILENAME 061', 'TP_ME_NEWFILENAME061', 061, 061, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 062', 'TP_ME_ID 062', 'TP_ME_NAME 062', 'TP_ME_TITLE 062', 'TP_ME_CONTENT 062', 'TP_ME_FILENAME 062', 'TP_ME_NEWFILENAME062', 062, 062, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 063', 'TP_ME_ID 063', 'TP_ME_NAME 063', 'TP_ME_TITLE 063', 'TP_ME_CONTENT 063', 'TP_ME_FILENAME 063', 'TP_ME_NEWFILENAME063', 063, 063, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 064', 'TP_ME_ID 064', 'TP_ME_NAME 064', 'TP_ME_TITLE 064', 'TP_ME_CONTENT 064', 'TP_ME_FILENAME 064', 'TP_ME_NEWFILENAME064', 064, 064, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 065', 'TP_ME_ID 065', 'TP_ME_NAME 065', 'TP_ME_TITLE 065', 'TP_ME_CONTENT 065', 'TP_ME_FILENAME 065', 'TP_ME_NEWFILENAME065', 065, 065, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 066', 'TP_ME_ID 066', 'TP_ME_NAME 066', 'TP_ME_TITLE 066', 'TP_ME_CONTENT 066', 'TP_ME_FILENAME 066', 'TP_ME_NEWFILENAME066', 066, 066, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 067', 'TP_ME_ID 067', 'TP_ME_NAME 067', 'TP_ME_TITLE 067', 'TP_ME_CONTENT 067', 'TP_ME_FILENAME 067', 'TP_ME_NEWFILENAME067', 067, 067, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 068', 'TP_ME_ID 068', 'TP_ME_NAME 068', 'TP_ME_TITLE 068', 'TP_ME_CONTENT 068', 'TP_ME_FILENAME 068', 'TP_ME_NEWFILENAME068', 068, 068, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 069', 'TP_ME_ID 069', 'TP_ME_NAME 069', 'TP_ME_TITLE 069', 'TP_ME_CONTENT 069', 'TP_ME_FILENAME 069', 'TP_ME_NEWFILENAME069', 069, 069, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 070', 'TP_ME_ID 070', 'TP_ME_NAME 070', 'TP_ME_TITLE 070', 'TP_ME_CONTENT 070', 'TP_ME_FILENAME 070', 'TP_ME_NEWFILENAME070', 070, 070, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 071', 'TP_ME_ID 071', 'TP_ME_NAME 071', 'TP_ME_TITLE 071', 'TP_ME_CONTENT 071', 'TP_ME_FILENAME 071', 'TP_ME_NEWFILENAME071', 071, 071, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 072', 'TP_ME_ID 072', 'TP_ME_NAME 072', 'TP_ME_TITLE 072', 'TP_ME_CONTENT 072', 'TP_ME_FILENAME 072', 'TP_ME_NEWFILENAME072', 072, 072, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 073', 'TP_ME_ID 073', 'TP_ME_NAME 073', 'TP_ME_TITLE 073', 'TP_ME_CONTENT 073', 'TP_ME_FILENAME 073', 'TP_ME_NEWFILENAME073', 073, 073, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 074', 'TP_ME_ID 074', 'TP_ME_NAME 074', 'TP_ME_TITLE 074', 'TP_ME_CONTENT 074', 'TP_ME_FILENAME 074', 'TP_ME_NEWFILENAME074', 074, 074, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 075', 'TP_ME_ID 075', 'TP_ME_NAME 075', 'TP_ME_TITLE 075', 'TP_ME_CONTENT 075', 'TP_ME_FILENAME 075', 'TP_ME_NEWFILENAME075', 075, 075, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 076', 'TP_ME_ID 076', 'TP_ME_NAME 076', 'TP_ME_TITLE 076', 'TP_ME_CONTENT 076', 'TP_ME_FILENAME 076', 'TP_ME_NEWFILENAME076', 076, 076, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 077', 'TP_ME_ID 077', 'TP_ME_NAME 077', 'TP_ME_TITLE 077', 'TP_ME_CONTENT 077', 'TP_ME_FILENAME 077', 'TP_ME_NEWFILENAME077', 077, 077, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 078', 'TP_ME_ID 078', 'TP_ME_NAME 078', 'TP_ME_TITLE 078', 'TP_ME_CONTENT 078', 'TP_ME_FILENAME 078', 'TP_ME_NEWFILENAME078', 078, 078, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 079', 'TP_ME_ID 079', 'TP_ME_NAME 079', 'TP_ME_TITLE 079', 'TP_ME_CONTENT 079', 'TP_ME_FILENAME 079', 'TP_ME_NEWFILENAME079', 079, 079, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 080', 'TP_ME_ID 080', 'TP_ME_NAME 080', 'TP_ME_TITLE 080', 'TP_ME_CONTENT 080', 'TP_ME_FILENAME 080', 'TP_ME_NEWFILENAME080', 080, 080, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 081', 'TP_ME_ID 081', 'TP_ME_NAME 081', 'TP_ME_TITLE 081', 'TP_ME_CONTENT 081', 'TP_ME_FILENAME 081', 'TP_ME_NEWFILENAME081', 081, 081, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 082', 'TP_ME_ID 082', 'TP_ME_NAME 082', 'TP_ME_TITLE 082', 'TP_ME_CONTENT 082', 'TP_ME_FILENAME 082', 'TP_ME_NEWFILENAME082', 082, 082, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 083', 'TP_ME_ID 083', 'TP_ME_NAME 083', 'TP_ME_TITLE 083', 'TP_ME_CONTENT 083', 'TP_ME_FILENAME 083', 'TP_ME_NEWFILENAME083', 083, 083, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 084', 'TP_ME_ID 084', 'TP_ME_NAME 084', 'TP_ME_TITLE 084', 'TP_ME_CONTENT 084', 'TP_ME_FILENAME 084', 'TP_ME_NEWFILENAME084', 084, 084, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 085', 'TP_ME_ID 085', 'TP_ME_NAME 085', 'TP_ME_TITLE 085', 'TP_ME_CONTENT 085', 'TP_ME_FILENAME 085', 'TP_ME_NEWFILENAME085', 085, 085, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 086', 'TP_ME_ID 086', 'TP_ME_NAME 086', 'TP_ME_TITLE 086', 'TP_ME_CONTENT 086', 'TP_ME_FILENAME 086', 'TP_ME_NEWFILENAME086', 086, 086, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 087', 'TP_ME_ID 087', 'TP_ME_NAME 087', 'TP_ME_TITLE 087', 'TP_ME_CONTENT 087', 'TP_ME_FILENAME 087', 'TP_ME_NEWFILENAME087', 087, 087, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 088', 'TP_ME_ID 088', 'TP_ME_NAME 088', 'TP_ME_TITLE 088', 'TP_ME_CONTENT 088', 'TP_ME_FILENAME 088', 'TP_ME_NEWFILENAME088', 088, 088, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 089', 'TP_ME_ID 089', 'TP_ME_NAME 089', 'TP_ME_TITLE 089', 'TP_ME_CONTENT 089', 'TP_ME_FILENAME 089', 'TP_ME_NEWFILENAME089', 089, 089, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 090', 'TP_ME_ID 090', 'TP_ME_NAME 090', 'TP_ME_TITLE 090', 'TP_ME_CONTENT 090', 'TP_ME_FILENAME 090', 'TP_ME_NEWFILENAME090', 090, 090, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 091', 'TP_ME_ID 091', 'TP_ME_NAME 091', 'TP_ME_TITLE 091', 'TP_ME_CONTENT 091', 'TP_ME_FILENAME 091', 'TP_ME_NEWFILENAME091', 091, 091, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 092', 'TP_ME_ID 092', 'TP_ME_NAME 092', 'TP_ME_TITLE 092', 'TP_ME_CONTENT 092', 'TP_ME_FILENAME 092', 'TP_ME_NEWFILENAME092', 092, 092, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 093', 'TP_ME_ID 093', 'TP_ME_NAME 093', 'TP_ME_TITLE 093', 'TP_ME_CONTENT 093', 'TP_ME_FILENAME 093', 'TP_ME_NEWFILENAME093', 093, 093, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 094', 'TP_ME_ID 094', 'TP_ME_NAME 094', 'TP_ME_TITLE 094', 'TP_ME_CONTENT 094', 'TP_ME_FILENAME 094', 'TP_ME_NEWFILENAME094', 094, 094, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 095', 'TP_ME_ID 095', 'TP_ME_NAME 095', 'TP_ME_TITLE 095', 'TP_ME_CONTENT 095', 'TP_ME_FILENAME 095', 'TP_ME_NEWFILENAME095', 095, 095, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 096', 'TP_ME_ID 096', 'TP_ME_NAME 096', 'TP_ME_TITLE 096', 'TP_ME_CONTENT 096', 'TP_ME_FILENAME 096', 'TP_ME_NEWFILENAME096', 096, 096, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 097', 'TP_ME_ID 097', 'TP_ME_NAME 097', 'TP_ME_TITLE 097', 'TP_ME_CONTENT 097', 'TP_ME_FILENAME 097', 'TP_ME_NEWFILENAME097', 097, 097, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 098', 'TP_ME_ID 098', 'TP_ME_NAME 098', 'TP_ME_TITLE 098', 'TP_ME_CONTENT 098', 'TP_ME_FILENAME 098', 'TP_ME_NEWFILENAME098', 098, 098, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 099', 'TP_ME_ID 099', 'TP_ME_NAME 099', 'TP_ME_TITLE 099', 'TP_ME_CONTENT 099', 'TP_ME_FILENAME 099', 'TP_ME_NEWFILENAME099', 099, 099, sysdate);
INSERT INTO TP_MUSTEAT (TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, TP_ME_CONTENT, TP_ME_FILENAME, TP_ME_NEWFILENAME, TP_ME_READCOUNT, TP_ME_DOWNCOUNT, TP_ME_REGDATE) VALUES ('TP_ME_PLACE 100', 'TP_ME_ID 100', 'TP_ME_NAME 100', 'TP_ME_TITLE 100', 'TP_ME_CONTENT 100', 'TP_ME_FILENAME 100', 'TP_ME_NEWFILENAME100', 100, 100, sysdate);

SELECT * FROM TP_MEMBER;

--RANKING
SELECT TP_ME_SEQ,
				 TP_ME_PLACE,
				 TP_ME_ID,
				 TP_ME_NAME,
				 TP_ME_TITLE,
				 TP_ME_CONTENT,
				 TP_ME_FILENAME,
			     TP_ME_NEWFILENAME,
			     TP_ME_READCOUNT,
				 TP_ME_DOWNCOUNT,
				 TP_ME_REGDATE,
				 TP_ME_LIKE
			     FROM (SELECT ROW_NUMBER()OVER(ORDER BY TP_ME_SEQ DESC)AS ROWNUM, 
				 	TP_ME_SEQ, TP_ME_PLACE, TP_ME_ID, TP_ME_NAME, TP_ME_TITLE, 
				   TP_ME_CONTENT,
				   TP_ME_FILENAME, TP_ME_NEWFILENAME,
				   TP_ME_READCOUNT, TP_ME_DOWNCOUNT,
				   TP_ME_REGDATE, TP_ME_LIKE
				   FROM TP_MUSTEAT 
				   ORDER BY TP_ME_READCOUNT DESC)
				   WHERE ROWNUM<=3;



INSERT INTO TP_MEMBER(TP_M_SEQ, TP_M_ID, TP_M_PWD, TP_M_NAME, TP_M_EMAIL, TP_M_DEL, TP_M_AUTH, TP_M_JOINDATE, TP_M_LASTLOGIN)
VALUES(TP_MEMBER_SEQ.NEXTVAL, 'vivi', 'vivi', '이수빈', 'vivianle', 0, 0, SYSDATE, SYSDATE)
CREATE TABLE TP_MEMBER
(
    TP_M_SEQ          NUMBER          NOT NULL, 
    TP_M_ID           VARCHAR2(50)    NULL, 
    TP_M_PWD          VARCHAR2(50)    NULL, 
    TP_M_NAME         VARCHAR2(20)    NULL, 
    TP_M_EMAIL        VARCHAR2(30)    NULL, 
    TP_M_DEL          NUMBER          NULL, 
    TP_M_AUTH         NUMBER          NULL, 
    TP_M_JOINDATE     DATE            NULL, 
    TP_M_LASTLOGIN    DATE            NULL, 
    CONSTRAINT TP_MEMBER_PK PRIMARY KEY (TP_M_SEQ, TP_M_NAME)
)
/

CREATE SEQUENCE TP_MEMBER_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TP_MEMBER_AI_TRG
BEFORE INSERT ON TP_MEMBER 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TP_MEMBER_SEQ.NEXTVAL
    INTO :NEW.TP_M_SEQ
    FROM DUAL;
END;

